version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:6.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: keycloak
    command:
      [
          '-b',
          '0.0.0.0',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Djboss.socket.binding.port-offset=1000',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "9080:9080"
      - "9443:9443"
      - "10990:10990"
  user-postgresql:
    image: postgres:12.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - ./user-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
  mongo1:
    image: mongo
    command: --replSet appointmentrs --bind_ip_all
  mongo2:
    image: mongo
    command: --replSet appointmentrs --bind_ip_all
  init-container:
    image: mongo
    depends_on:
      - mongo1
      - mongo2
    volumes:
      - ./rs:/rs
    command: ./rs/init.sh
  appointment-service:
    image: appointment-service
    environment:
      - SPRING_DATA_MONGODB.URI=mongodb://localhost,mongo2/test?replicaSet=appointmentrs
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER-URI=http://keycloak:9080/auth/realms/medical-appointment
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:29092
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on:
      - mongo1
      - mongo2
      - kafka
      - keycloak
  idp-manager-service:
    image: idp-manager-service
    environment:
      - KEYCLOAK_SERVERURL=http://keycloak:9080/auth
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:29092
    ports:
      - "8082:8082"
    restart: on-failure
    depends_on:
      - keycloak
      - kafka
  user-service:
    image: user-service
    environment:
      - KEYCLOAK_SERVERURL=http://keycloak:9080/auth
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:29092
      - SPRING_R2DBC_URL=r2dbc:postgresql://user-postgresql:5432
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - user-postgresql
      - keycloak
