spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432
    name: user
    username: user
    password: user
  cloud:
    function:
      definition: userEventSupplier
    stream:
      bindings:
        userEventSupplier-out-0:
          destination: user.events

server:
  port: 8081
