spring:
  application:
    name: idp-manager-service
  cloud:
    function:
      definition: onUserEvent
    stream:
      bindings:
        onUserEvent-in-0:
          destination: user.events
          group: ${spring.application.name}-user-events-handler

keycloak:
  serverUrl: http://localhost:9080/auth
  realm: medical-appointment
  clientId: internal
  clientSecret: internal
  username: admin
  password: admin

server:
  port: 8082
