spring:
  application:
    name: appointment-service
  cloud:
    function:
      definition: onUserEvent
    stream:
      bindings:
        onUserEvent-in-0:
          destination: user.events
          group: ${spring.application.name}-user-events-handler
  data:
    mongodb:
      uri: mongodb://mongo1,mongo2/test?replicaSet=appointmentrs
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/auth/realms/medical-appointment
        registration:
          oidc:
            client-id: internal
            client-secret: internal

appointment:
  weekdays: 5
  startSlotHour: 9
  endSlotHour: 19

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
