spring:
  application:
    name: appointment-service
  cloud:
    function:
      definition: onUserEvent
    stream:
      bindings:
        onUserEvent-in-0:
          destination: user.events
          group: ${spring.application.name}-user-events-handler
  data:
    mongodb:
      database: appointmentdb
      username: appointmentUser
      password: Pa$$w0rd123

appointment:
  weekdays: 5
  startSlotHour: 9
  endSlotHour: 19

server:
  port: 8083

